services:
  web_nginx:
    image: nginx:latest
    container_name: web_nginx
    restart: always
    networks:
      - full_cycle_network
    ports:
      - "8080:80"
    depends_on:
      - node_app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  node_app:
    build:
      context: node
    container_name: node_app
    entrypoint: dockerize -wait tcp://node_db:3306 -timeout 20s node /usr/src/app/index.js
    networks:
      - full_cycle_network
    depends_on:
      - node_db
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules

  node_db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: node_db
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - full_cycle_network

networks:
  full_cycle_network:
    driver: bridge